# Use the official Node.js 20 image from the Docker Hub
FROM node:20

# Install dependencies for headless Chromium (Puppeteer/Playwright)
RUN apt-get update && apt-get install -y \
    wget \
    gnupg \
    ca-certificates \
    fonts-liberation \
    libappindicator3-1 \
    libasound2 \
    libatk1.0-0 \
    libcups2 \
    libdbus-1-3 \
    libdrm2 \
    libx11-xcb1 \
    libxcomposite1 \
    libxdamage1 \
    libxext6 \
    libxfixes3 \
    libnss3 \
    libnspr4 \
    libxrandr2 \
    libgbm1 \
    libgtk-3-0 \
    libglib2.0-0 \
    libatk-bridge2.0-0 \
    libxshmfence1 \
    lsb-release \
    xdg-utils \
    libu2f-udev \
    libvulkan1 \
    libcurl4

# Install Google Chrome Stable and fonts
# Note: this installs the necessary libs to make the browser work with Puppeteer.
RUN apt-get update && apt-get install curl gnupg -y \
  && curl --location --silent https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - \
  && sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' \
  && apt-get update \
  && apt-get install google-chrome-stable -y --no-install-recommends \
  && rm -rf /var/lib/apt/lists/*


# Set the working directory inside the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json (if available) to the working directory
COPY package*.json ./

# Install npm dependencies
RUN npm install --omit=dev

# Copy the rest of the application code to the working directory
COPY . .

# Expose the port that your app will run on (if applicable)
EXPOSE 3000

# Set environment variable to disable the sandbox in Chromium
ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD true

# Start the application by running the specific script (mainCompany.js)
CMD ["node", "backgroundJobs/profileUploaderJob.js"]

